### ISSUE TITLE
Controls covered by browser bars iPhone 8

### ISSUE THREAD

**Issue by BigAB** [Jorger/mr-square-game-report-bugs#1]
First off, this is a great game, and very nicely implemented.

On my iPhone 8 the browser controls cover up the game controls on the top and bottom:

#### Browser (emulating iPhone)
<img width="285" alt="Screen Shot Browser" src="https://user-images.githubusercontent.com/76821/88218475-5a572580-cc1d-11ea-9ebc-e1ec7aa72fe2.png">

#### iPhone Safari
<img width="285" alt="Screen Shot Browser" src="https://user-images.githubusercontent.com/76821/88218629-85417980-cc1d-11ea-8411-669c41bbe5be.PNG"/>

#### iPhone Chrome
<img width="285" alt="Screen Shot Browser" src="https://user-images.githubusercontent.com/76821/88218643-8e324b00-cc1d-11ea-9f09-3e021175e3fb.PNG" />

**Comment by Jorger** [comment]
Hi @BigAB, thank you very much for your comments, I'll fix it 💯

**Comment by Jorger** [comment]
Hi @BigAB I already fix the issue on iOS.

An event is fired to update the service worker

![update](https://i.ibb.co/YLtfFgd/update.png)

This is the result:

**iPhone 8**

![iphone8](https://i.ibb.co/FzYhtz3/iphone8.png)

**iPhone 8 - Installed**

![iphone82](https://i.ibb.co/bdsHnFq/iphone8installed.png)

I tested it in an emulator, since I don't have a real device 😄 

Thank you very much for reporting the bug 👍
