### ISSUE TITLE
Sometimes Squares on the path disapear.

### ISSUE THREAD

**Issue by josemariogutierrez** [Jorger/mr-square-game-report-bugs#2]
Sometimes when the character makes its path, a few squares disappear, check the gif for a better understanding.
This is running on an phone with android 9, installed as a standalone app. It happened on various levels, not only the 5-5.

![bug-2](https://user-images.githubusercontent.com/27037672/88411398-7a155780-cd9d-11ea-84b4-0f0f17a73a43.gif)

**Comment by Jorger** [comment]
Hi @josemariogutierrez I think I solved the problem 😀 , it was difficult, because it only happens in mobile devices 😞 , to avoid the loss of blocks, now I keep the route through which the character has passed, when the character stops valid if the route contains the blocks.

If a block is lost, I show a message to indicate it in the console, it is only for debugging.

![console](https://i.ibb.co/hsDn118/Captura-de-pantalla-2020-07-29-a-las-2-20-32-p-m.png)

Thank you very much for your feedback 🥇 

If you find another issue, don't hesitate to notify me 👍
